.nh
.TH "KUBECONFIG-MANAGER" "1" "Jan 0001" "kubeconfig-manager" ""

.SH NAME
kcm-alert-show - Show alert policy for a kubeconfig


.SH SYNOPSIS
\fBkcm alert show  [flags]\fP


.SH DESCRIPTION
Show alert policy for a kubeconfig


.SH OPTIONS
\fB--dir\fP=""
	Kubeconfig directory (default: ~/.kube)

.PP
\fB-h\fP, \fB--help\fP[=false]
	help for show


.SH SEE ALSO
\fBkcm-alert(1)\fP
