.nh
.TH "KUBECONFIG-MANAGER" "1" "Jan 0001" "kubeconfig-manager" ""

.SH NAME
kcm-alert-enable - Enable alerts (file-level, or --context for one context only)


.SH SYNOPSIS
\fBkcm alert enable  [flags]\fP


.SH DESCRIPTION
Enable alerts (file-level, or --context for one context only)


.SH OPTIONS
\fB--context\fP=""
	Apply to this context only (default: file-level)

.PP
\fB--dir\fP=""
	Kubeconfig directory (default: ~/.kube)

.PP
\fB-h\fP, \fB--help\fP[=false]
	help for enable


.SH SEE ALSO
\fBkcm-alert(1)\fP
