.nh
.TH "KUBECONFIG-MANAGER" "1" "Jan 0001" "kubeconfig-manager" ""

.SH NAME
kcm-tag-add - Add tags to a kubeconfig


.SH SYNOPSIS
\fBkcm tag add   [flags]\fP


.SH DESCRIPTION
Add tags to a kubeconfig


.SH OPTIONS
\fB--dir\fP=""
	Kubeconfig directory (default: ~/.kube)

.PP
\fB-h\fP, \fB--help\fP[=false]
	help for add


.SH SEE ALSO
\fBkcm-tag(1)\fP
