.nh
.TH "KUBECONFIG-MANAGER" "1" "Jan 0001" "kubeconfig-manager" ""

.SH NAME
kcm-alert - Configure destructive-action alerts per kubeconfig or context


.SH SYNOPSIS
\fBkcm alert [flags]\fP


.SH DESCRIPTION
Configure destructive-action alerts per kubeconfig or context


.SH OPTIONS
\fB-h\fP, \fB--help\fP[=false]
	help for alert


.SH SEE ALSO
\fBkcm(1)\fP, \fBkcm-alert-disable(1)\fP, \fBkcm-alert-enable(1)\fP, \fBkcm-alert-show(1)\fP
