.nh
.TH "KUBECONFIG-MANAGER" "1" "Jan 0001" "kubeconfig-manager" ""

.SH NAME
kcm-helm-guard-disable - Disable the helm guard globally (default) or override per --file


.SH SYNOPSIS
\fBkcm helm-guard disable [flags]\fP


.SH DESCRIPTION
Disable the helm guard globally (default) or override per --file


.SH OPTIONS
\fB--dir\fP=""
	Kubeconfig directory (default: ~/.kube)

.PP
\fB--file\fP=""
	Apply only to this kubeconfig (default: global)

.PP
\fB-h\fP, \fB--help\fP[=false]
	help for disable


.SH SEE ALSO
\fBkcm-helm-guard(1)\fP
