.nh
.TH "KUBECONFIG-MANAGER" "1" "Jan 0001" "kubeconfig-manager" ""

.SH NAME
kcm-tag-list - List tags for one kubeconfig (with per-context rows) or all kubeconfigs


.SH SYNOPSIS
\fBkcm tag list [file] [flags]\fP


.SH DESCRIPTION
List tags for one kubeconfig (with per-context rows) or all kubeconfigs


.SH OPTIONS
\fB--context\fP=""
	Apply to this context only (default: file-level)

.PP
\fB--dir\fP=""
	Kubeconfig directory (default: ~/.kube)

.PP
\fB-h\fP, \fB--help\fP[=false]
	help for list


.SH SEE ALSO
\fBkcm-tag(1)\fP
