.nh
.TH "KUBECONFIG-MANAGER" "1" "Jan 0001" "kubeconfig-manager" ""

.SH NAME
kcm-tag-palette-list - Show the current palette


.SH SYNOPSIS
\fBkcm tag palette list [flags]\fP


.SH DESCRIPTION
Show the current palette


.SH OPTIONS
\fB-h\fP, \fB--help\fP[=false]
	help for list


.SH SEE ALSO
\fBkcm-tag-palette(1)\fP
