.nh
.TH "KUBECONFIG-MANAGER" "1" "Jan 0001" "kubeconfig-manager" ""

.SH NAME
kcm-helm-guard-remove-pattern - Drop one or more patterns from the existing list


.SH SYNOPSIS
\fBkcm helm-guard remove-pattern  [flags]\fP


.SH DESCRIPTION
Drop one or more patterns from the existing list


.SH OPTIONS
\fB--dir\fP=""
	Kubeconfig directory (default: ~/.kube)

.PP
\fB--file\fP=""
	Apply only to this kubeconfig (default: global)

.PP
\fB-h\fP, \fB--help\fP[=false]
	help for remove-pattern


.SH SEE ALSO
\fBkcm-helm-guard(1)\fP
