.nh
.TH "KUBECONFIG-MANAGER" "1" "Jan 0001" "kubeconfig-manager" ""

.SH NAME
kcm-tag - Manage tags on kubeconfig files


.SH SYNOPSIS
\fBkcm tag [flags]\fP


.SH DESCRIPTION
Manage tags on kubeconfig files


.SH OPTIONS
\fB-h\fP, \fB--help\fP[=false]
	help for tag


.SH SEE ALSO
\fBkcm(1)\fP, \fBkcm-tag-add(1)\fP, \fBkcm-tag-list(1)\fP, \fBkcm-tag-remove(1)\fP
