.nh
.TH "KUBECONFIG-MANAGER" "1" "Jan 0001" "kubeconfig-manager" ""

.SH NAME
kcm-kubectl - Run kubectl through the destructive-action guard


.SH SYNOPSIS
\fBkcm kubectl [args...] [flags]\fP


.SH DESCRIPTION
Run kubectl through the destructive-action guard


.SH OPTIONS
\fB-h\fP, \fB--help\fP[=false]
	help for kubectl


.SH SEE ALSO
\fBkcm(1)\fP
