.nh
.TH "KUBECONFIG-MANAGER" "1" "Jan 0001" "kubeconfig-manager" ""

.SH NAME
kcm-context-rename - Rename a context and move its per-context state (tags, alerts) to the new name


.SH SYNOPSIS
\fBkcm context rename    [flags]\fP


.SH DESCRIPTION
Rename a context and move its per-context state (tags, alerts) to the new name


.SH OPTIONS
\fB--dir\fP=""
	Kubeconfig directory (default: ~/.kube)

.PP
\fB-h\fP, \fB--help\fP[=false]
	help for rename


.SH SEE ALSO
\fBkcm-context(1)\fP
