.nh
.TH "KUBECONFIG-MANAGER" "1" "Jan 0001" "kubeconfig-manager" ""

.SH NAME
kcm-alert-show - Show alert policy (file-level, per-context, or --context to filter)


.SH SYNOPSIS
\fBkcm alert show  [flags]\fP


.SH DESCRIPTION
Show alert policy (file-level, per-context, or --context to filter)


.SH OPTIONS
\fB--context\fP=""
	Apply to this context only (default: file-level)

.PP
\fB--dir\fP=""
	Kubeconfig directory (default: ~/.kube)

.PP
\fB-h\fP, \fB--help\fP[=false]
	help for show


.SH SEE ALSO
\fBkcm-alert(1)\fP
