.nh
.TH "KUBECONFIG-MANAGER" "1" "Jan 0001" "kubeconfig-manager" ""

.SH NAME
kcm-helm-guard - Configure the helm values-path / context mismatch guard


.SH SYNOPSIS
\fBkcm helm-guard [flags]\fP


.SH DESCRIPTION
Configure the helm values-path / context mismatch guard


.SH OPTIONS
\fB-h\fP, \fB--help\fP[=false]
	help for helm-guard


.SH SEE ALSO
\fBkcm(1)\fP, \fBkcm-helm-guard-disable(1)\fP, \fBkcm-helm-guard-enable(1)\fP, \fBkcm-helm-guard-set-pattern(1)\fP, \fBkcm-helm-guard-show(1)\fP
