.nh
.TH "KUBECONFIG-MANAGER" "1" "Jan 0001" "kubeconfig-manager" ""

.SH NAME
kcm-context - Rename or delete contexts within a kubeconfig file


.SH SYNOPSIS
\fBkcm context [flags]\fP


.SH DESCRIPTION
Rename or delete contexts within a kubeconfig file


.SH OPTIONS
\fB-h\fP, \fB--help\fP[=false]
	help for context


.SH SEE ALSO
\fBkcm(1)\fP, \fBkcm-context-delete(1)\fP, \fBkcm-context-rename(1)\fP
