.nh
.TH "KUBECONFIG-MANAGER" "1" "Jan 0001" "kubeconfig-manager" ""

.SH NAME
kcm-show - Show contexts, clusters, and users of a kubeconfig file


.SH SYNOPSIS
\fBkcm show  [flags]\fP


.SH DESCRIPTION
Show contexts, clusters, and users of a kubeconfig file


.SH OPTIONS
\fB--dir\fP=""
	Kubeconfig directory for bare-name lookups (default: ~/.kube)

.PP
\fB-h\fP, \fB--help\fP[=false]
	help for show


.SH SEE ALSO
\fBkcm(1)\fP
