.nh
.TH "KUBECONFIG-MANAGER" "1" "Jan 0001" "kubeconfig-manager" ""

.SH NAME
kcm-alert-disable - Disable alerts for a kubeconfig


.SH SYNOPSIS
\fBkcm alert disable  [flags]\fP


.SH DESCRIPTION
Disable alerts for a kubeconfig


.SH OPTIONS
\fB--dir\fP=""
	Kubeconfig directory (default: ~/.kube)

.PP
\fB-h\fP, \fB--help\fP[=false]
	help for disable


.SH SEE ALSO
\fBkcm-alert(1)\fP
