.nh
.TH "KUBECONFIG-MANAGER" "1" "Jan 0001" "kubeconfig-manager" ""

.SH NAME
kcm-install-shell-hook - Install shell integration (kcm function and kubectl alias)


.SH SYNOPSIS
\fBkcm install-shell-hook [flags]\fP


.SH DESCRIPTION
Installs a fenced block in your shell rc with two things:
  1. A kcm() function that evaluates the export snippet from \fBkcm use\fR and \fBkcm tui\fR\&.
  2. An alias so plain \fBkubectl\fR routes through kcm's destructive-action guard.

.PP
Pass --no-alias-kubectl to skip the kubectl alias (alerts will only fire when you
run \fBkcm kubectl ...\fR explicitly).


.SH OPTIONS
\fB--alias-helm\fP[=false]
	Also alias helm to route through the helm-guard (opt-in)

.PP
\fB-h\fP, \fB--help\fP[=false]
	help for install-shell-hook

.PP
\fB--no-alias-kubectl\fP[=false]
	Skip the kubectl alias (alerts won't fire for plain kubectl invocations)

.PP
\fB--rc\fP=""
	rc file path (default depends on shell)

.PP
\fB--shell\fP=""
	bash, zsh, or pwsh (auto-detected if unset)


.SH SEE ALSO
\fBkcm(1)\fP
