.nh
.TH "KUBECONFIG-MANAGER" "1" "Jan 0001" "kubeconfig-manager" ""

.SH NAME
kcm-tui - Launch the interactive TUI


.SH SYNOPSIS
\fBkcm tui [flags]\fP


.SH DESCRIPTION
Launch the interactive TUI


.SH OPTIONS
\fB--dir\fP=""
	Kubeconfig directory (default: ~/.kube)

.PP
\fB-h\fP, \fB--help\fP[=false]
	help for tui

.PP
\fB--shell\fP=""
	Shell to emit for: bash, zsh, pwsh (auto-detected if unset)


.SH SEE ALSO
\fBkcm(1)\fP
