.nh
.TH "KUBECONFIG-MANAGER" "1" "Jan 0001" "kubeconfig-manager" ""

.SH NAME
kcm-contexts - List contexts in the default kubeconfig (~/.kube/config)


.SH SYNOPSIS
\fBkcm contexts [flags]\fP


.SH DESCRIPTION
List contexts in the default kubeconfig (~/.kube/config)


.SH OPTIONS
\fB--file\fP=""
	Kubeconfig file to inspect (default: ~/.kube/config)

.PP
\fB-h\fP, \fB--help\fP[=false]
	help for contexts


.SH SEE ALSO
\fBkcm(1)\fP
