.nh
.TH "KUBECONFIG-MANAGER" "1" "Jan 0001" "kubeconfig-manager" ""

.SH NAME
kcm-helm-guard-add-pattern - Append one or more patterns to the existing list


.SH SYNOPSIS
\fBkcm helm-guard add-pattern  [flags]\fP


.SH DESCRIPTION
Append one or more patterns to the existing list


.SH OPTIONS
\fB--dir\fP=""
	Kubeconfig directory (default: ~/.kube)

.PP
\fB--file\fP=""
	Apply only to this kubeconfig (default: global)

.PP
\fB-h\fP, \fB--help\fP[=false]
	help for add-pattern


.SH SEE ALSO
\fBkcm-helm-guard(1)\fP
