.nh
.TH "KUBECONFIG-MANAGER" "1" "Jan 0001" "kubeconfig-manager" ""

.SH NAME
kcm-init - First-run walkthrough: palette seed, shell hook, starship snippet


.SH SYNOPSIS
\fBkcm init [flags]\fP


.SH DESCRIPTION
Interactive setup that asks a handful of questions and performs the common first-time steps: adding a starter tag palette, installing the shell hook (with optional kubectl/helm aliases), and printing a starship custom-module snippet. Pass --yes to skip prompts and accept every default (useful for automation and for testing).


.SH OPTIONS
\fB-h\fP, \fB--help\fP[=false]
	help for init

.PP
\fB--rc\fP=""
	Override rc file path for the shell hook install (default: detected per shell)

.PP
\fB--skip-palette\fP[=false]
	Do not seed the tag palette

.PP
\fB--skip-shell-hook\fP[=false]
	Do not install the shell hook

.PP
\fB--yes\fP[=false]
	Skip interactive prompts and accept defaults


.SH SEE ALSO
\fBkcm(1)\fP
