.nh
.TH "KUBECONFIG-MANAGER" "1" "Jan 0001" "kubeconfig-manager" ""

.SH NAME
kcm-rename - Rename a kubeconfig file on disk (metadata re-binds automatically)


.SH SYNOPSIS
\fBkcm rename   [flags]\fP


.SH DESCRIPTION
Rename a kubeconfig file on disk (metadata re-binds automatically)


.SH OPTIONS
\fB--dir\fP=""
	Kubeconfig directory (default: ~/.kube)

.PP
\fB--dry-run\fP[=false]
	Print the planned change without touching the file or state

.PP
\fB--force\fP[=false]
	Overwrite destination if it exists

.PP
\fB-h\fP, \fB--help\fP[=false]
	help for rename


.SH SEE ALSO
\fBkcm(1)\fP
