.nh
.TH "KUBECONFIG-MANAGER" "1" "Jan 0001" "kubeconfig-manager" ""

.SH NAME
kcm-tag-palette-add - Add tags to the global palette


.SH SYNOPSIS
\fBkcm tag palette add  [flags]\fP


.SH DESCRIPTION
Add tags to the global palette


.SH OPTIONS
\fB-h\fP, \fB--help\fP[=false]
	help for add


.SH SEE ALSO
\fBkcm-tag-palette(1)\fP
