.nh
.TH "KUBECONFIG-MANAGER" "1" "Jan 0001" "kubeconfig-manager" ""

.SH NAME
kcm-tag-remove - Remove tags (file-level, or --context for one context only)


.SH SYNOPSIS
\fBkcm tag remove   [flags]\fP


.SH DESCRIPTION
Remove tags (file-level, or --context for one context only)


.SH OPTIONS
\fB--context\fP=""
	Apply to this context only (default: file-level)

.PP
\fB--dir\fP=""
	Kubeconfig directory (default: ~/.kube)

.PP
\fB-h\fP, \fB--help\fP[=false]
	help for remove


.SH SEE ALSO
\fBkcm-tag(1)\fP
