.nh
.TH "KUBECONFIG-MANAGER" "1" "Jan 0001" "kubeconfig-manager" ""

.SH NAME
kcm-list - List kubeconfig files in the managed directory


.SH SYNOPSIS
\fBkcm list [flags]\fP


.SH DESCRIPTION
List kubeconfig files in the managed directory


.SH OPTIONS
\fB--dir\fP=""
	Kubeconfig directory (default: ~/.kube)

.PP
\fB-h\fP, \fB--help\fP[=false]
	help for list

.PP
\fB-v\fP, \fB--verbose\fP[=false]
	Show files that were skipped because they couldn't be parsed as kubeconfigs


.SH SEE ALSO
\fBkcm(1)\fP
