.nh
.TH "KUBECONFIG-MANAGER" "1" "Jan 0001" "kubeconfig-manager" ""

.SH NAME
kcm - Manage kubeconfig files and kubectl contexts


.SH SYNOPSIS
\fBkcm [flags]\fP


.SH DESCRIPTION
kubeconfig-manager (kcm) is a TUI + CLI for managing local kubeconfig files and kubectl contexts, with tagging and destructive-action guardrails.


.SH OPTIONS
\fB-h\fP, \fB--help\fP[=false]
	help for kcm


.SH SEE ALSO
\fBkcm-alert(1)\fP, \fBkcm-contexts(1)\fP, \fBkcm-import(1)\fP, \fBkcm-install-shell-hook(1)\fP, \fBkcm-kubectl(1)\fP, \fBkcm-list(1)\fP, \fBkcm-merge(1)\fP, \fBkcm-prune(1)\fP, \fBkcm-rename(1)\fP, \fBkcm-show(1)\fP, \fBkcm-split(1)\fP, \fBkcm-tag(1)\fP, \fBkcm-tui(1)\fP, \fBkcm-uninstall-shell-hook(1)\fP, \fBkcm-use(1)\fP
